### ISSUE TITLE
'mode.Worker' overrides logging configuration

### ISSUE THREAD

**Issue by nickgashkov** [ask/mode#46]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Mode.

## Steps to reproduce

1. Setup logging by yourself.
2. Call `mode.Worker.execute_from_commandline`.

Relevant code snippet:

```python
import mode
import logging.config


if __name__ == '__main__':
    logging.config.dictConfig(
        ...  # Some kind of setup.
    )

    service = mode.Service()
    worker = mode.Worker(service)
    worker.execute_from_commandline()
```
## Expected behavior

Logging behaves as it was configured (e.g. log records are formatted based on `logging.config`).

## Actual behavior

Logging configuration is overridden by `mode.Worker#_setup_logging`.

## Full traceback

—

# Versions

* Python version: 3.7.3
* Mode version: 3.0.7
* Operating system: macOS

**Comment by ask** [comment]
This is by design. There are many libraries that misbehave and misconfigure logging, sometimes even resulting in no output at all.  This scenario is indistinguishable from the process hanging or doing nothing, even if it's really working. For this reason we hijack the logger configuration to ensure there is always output.

You can pass in the logger configuration: ```Worker(logging_config={...})```.

We can add a flag to not setup logging at all also, but it cannot be the default behavior.

**Comment by nickgashkov** [comment]
@ask, I see, thanks for the reply!
